const data = [
    {
        name: "Hanuman Garhi",
        address: "Ram Nagar, Ayodhya, Uttar Pradesh 224123",
        uri: require('../Assests/t1.png'),
        uri2: require('../Assests/tp1.png'),
        description: "Hanuman Garhi, a celestial abode perched atop a hillock in the sacred city of Ayodhya, is a beacon of devotion and a testament to the unwavering loyalty of Lord Hanuman.This revered temple, dedicated to the mighty monkey god immortalized in the Ramayana, stands as a symbol of strength, humility, and boundless devotion.\n\nThe journey to Hanuman Garhi begins with a climb up a flight of orange- hued steps, each step echoing with the echoes of prayers and hymns.As devotees ascend, they are greeted by the imposing figure of Lord Hanuman, his orange countenance radiating divine energy.The temple complex, adorned with intricate carvings and vibrant paintings, exudes a spiritual vibrancy that captivates all who enter.\n\nDevotees flock to Hanuman Garhi to seek the blessings of Bajrangbali, the revered deity known for his unwavering dedication to Lord Rama.The air is filled with the melodious strains of devotional songs, creating an atmosphere charged with reverence.Pilgrims, young and old, come to offer their prayers and witness the panoramic views of Ayodhya from the temple's vantage point.\n\nThe sanctum sanctorum enshrines an idol of Lord Hanuman in a deep state of meditation, his gaze fixed on the divine ideals of righteousness and devotion. It is believed that a visit to Hanuman Garhi brings strength, courage, and protection from evil forces, making it a cherished pilgrimage site for those navigating life's challenges.\n\nThe temple's architecture, a harmonious blend of Rajput and South Indian styles, adds to its cultural and historical significance. The sprawling courtyard, adorned with vibrant flowers and sacred trees, invites contemplation and introspection. As the temple bells resonate through the air, they seem to echo the devotion of centuries, creating a timeless connection between the mortal and the divine.\n\nHanuman Garhi, with its sacred ambiance and spiritual grandeur, remains an enduring symbol of devotion and an integral part of Ayodhya's cultural and religious landscape.Pilgrims and visitors alike are drawn to this celestial haven, where the spirit of Hanuman continues to inspire and uplift all who seek solace in his divine presence.",
        disTime: "2.5 km/40min",
        reviews: "78K",
    },
    {
        name: "Sarayu Ghat",
        address: "Ram Nagar, Ayodhya, Uttar Pradesh 224123",
        uri: require('../Assests/t2.png'),
        uri2: require('../Assests/tp2.png'),
        description: "Sarayu Ghat, nestled along the meandering banks of the sacred Sarayu River in Ayodhya, stands as a timeless testament to the rich tapestry of Hindu spirituality and mythology.This revered riverbank holds profound significance, not only in the hearts of local devotees but also for pilgrims who journey from afar to partake in its divine aura.\n\nA visit to Sarayu Ghat is a spiritual odyssey, where the tranquil waters of the Sarayu River evoke a sense of purity and sanctity.Pilgrims engage in a variety of religious rituals, from traditional ceremonies to sacred baths, seeking spiritual cleansing and a connection with the divine.The rhythmic chants of hymns and the fragrance of incense permeate the air, creating an atmosphere charged with devotion.\n\nThe spiritual importance of Sarayu Ghat is deeply intertwined with the illustrious Ramayana, one of Hinduism's great epics. Legend has it that this very ghat is where Lord Rama, accompanied by his divine consort Sita and unwavering brother Lakshmana, embarked on his celestial journey, leaving the mortal realm to return to his heavenly abode. The steps of the ghat, worn smooth by centuries of devotees, seem to echo with the footsteps of this divine trio. \n\nBeyond its mythological resonance, Sarayu Ghat serves as a quiet refuge for meditation and contemplation.The river's gentle flow mirrors the passage of time, inviting visitors to reflect on life's transient nature and seek solace in the eternal.The ghat's architecture, adorned with intricate carvings and sculptures, pays homage to the cultural and artistic heritage of the region. \n\nEvery stone, every ripple in the sacred waters, tells a story—a story of faith, devotion, and the enduring connection between the mortal and the divine.Sarayu Ghat, with its timeless charm and spiritual allure, stands as a living monument to the cultural and religious heritage of Ayodhya, inviting all who visit to immerse themselves in the divine currents of its storied waters.",
        disTime: "4.58 km/1hr 15min",
    },
    {
        name: "Kanak Bhawan",
        address: "Ram Nagar, Ayodhya, Uttar Pradesh 224123",
        uri: require('../Assests/t3.png'),
        uri2: require('../Assests/tp3.png'),
        description: `Kanak Bhawan, a resplendent marvel nestled in the heart of Ayodhya, unfolds a divine tapestry of art, devotion, and mythological significance. Dedicated to Lord Rama and his divine consort Sita, this sacred abode transcends the earthly realm, captivating pilgrims and visitors with its enchanting allure.\n\nAs the doors of Kanak Bhawan open, one is greeted by the exquisite artwork that adorns its walls. The temple's name, "Kanak Bhawan," translates to "Golden House," and true to its name, the interior is adorned with golden-hued deities and intricate carvings that narrate the timeless tales of the Ramayana. Pilgrims are enveloped in an atmosphere of reverence and divinity, immersed in the sanctity of the space.\n\nThe legend associated with Kanak Bhawan is as captivating as its architecture. According to popular belief, Sita, in a divine gesture, received this ornate palace as a gift from her father, King Janaka, during her marriage to Lord Rama. The temple, therefore, stands as a symbol of the eternal bond between Rama and Sita, their love immortalized in the intricate details of the temple's design.\n\nDevotees throng to Kanak Bhawan to witness the divine presence of Lord Rama and Sita. The main sanctum enshrines idols of the divine couple, their divine countenances radiating compassion and grace. The rituals and prayers conducted within the temple echo with the melodic chanting of hymns, creating an ambiance that transcends the mundane and invites worshippers into the realm of the divine.\n\nThe temple's architecture seamlessly blends various styles, including Rajput and South Indian influences, reflecting the rich cultural tapestry of Ayodhya. The sprawling courtyard, adorned with blooming flowers and ancient trees, offers a tranquil space for contemplation and spiritual introspection. Pilgrims leave Kanak Bhawan with a sense of spiritual fulfillment, carrying with them the blessings of Lord Rama and Sita.\n\nKanak Bhawan, with its golden splendor and spiritual resonance, stands as a testament to the enduring love and devotion depicted in the Ramayana. It invites pilgrims to embark on a sacred journey, where the divine presence of Rama and Sita continues to inspire and uplift those who seek solace within its hallowed walls.`,
        disTime: "4.5 km/1hr 10min",
        reviews: "67K",
    },

]


export default data;



